Fix LivyOperatorAsync example DAG
astronomer/astronomer-providers pull request #252
Opened 2022-04-20 15:32 UTC by pankajkoti

The LivyOperatorAsync example DAG is failing as part of the integration
tests on staging environment. The reason for the failure is that the DAG is
referring to AWS environment variables different than what has been
configured in the staging deployment. This change renames such AWS 
environment variables to be consistent with other example DAG and the
same have been set in the staging deployment environment.

Closes: https://github.com/astronomer/astronomer-providers/issues/237

2022-04-20 15:33 UTC, pankajkoti commented
Resolved initial issues where inconsistent variable names were causing connection error.

We still are facing issues, with the following error being next:
`{'Code': 'VALIDATION_ERROR', 'Message': 'The given SSH key name was invalid'}` Will look into this next.

2022-04-21 09:56 UTC, pankajkoti commented
> {'Code': 'VALIDATION_ERROR', 'Message': 'The given SSH key name was invalid'}

This issue was due to inconsistent regions. @sunank200 helped pointing this out and the example DAG runs fine now with `us-east-2`

2022-04-21 09:56 UTC, sunank200 commented
`aws-region-name` has to be `us-east-2`. This issue should be fixed now.

2022-04-21 10:30 UTC, pankajastro approved these changes

2022-04-21 10:38 UTC, rajaths010494 approved these changes

2022-04-21 11:13 UTC, phanikumv requested changes
Please update the description to summarize what we are doing

2022-04-21 11:32 UTC, phanikumv approved these changes

2022-04-21 11:32 UTC, merged