[Dataproc] Optimize Example DAG And Push Job ID in XCOM
astronomer/astronomer-providers pull request #399
Opened 2022-05-30 13:34 UTC by pankajastro

This PR fix 
- Push dataproc Job Id instead of success message in xcom as sync version does 
- Fix test as per above change
- Remove kwargs param from DataProcSubmitTrigger, Since this does not require 
- Delete cluster and delete bucket task should always run in the example
- Optimize DAG. earlier it was creating 7 instances now it will create 3

Closes: #400

2022-05-30 14:36 UTC, phanikumv approved these changes

2022-05-30 14:37 UTC, phanikumv reviewed
@pankajastro change num_instances to 1 for worker_config as well please

2022-05-30 14:41 UTC, pankajkoti reviewed
Can you please add to the description why do we need to push `job_id` to `XCOM`? Is it needed somewhere?
In general, in my opinion, I feel we should add `what` and `why` in the PR description.
Reference: https://cbea.ms/git-commit/#why-not-how

2022-05-30 14:47 UTC, bharanidharan14 approved these changes

2022-05-30 15:20 UTC, pankajastro commented
> @pankajastro change num_instances to 1 for worker_config as well please

If the worker node is 1 then getting this error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.9/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Worker configuration must contain two or more workers: '1'"
```

2022-05-30 15:22 UTC, pankajastro commented
> Can you please add to the description why do we need to push `job_id` to `XCOM`? Is it needed somewhere? In general, in my opinion, I feel we should add `what` and `why` in the PR description. Reference: https://cbea.ms/git-commit/#why-not-how

Since the sync version does the same so I am also doing here  I have added reference in #400

2022-05-30 16:21 UTC, pankajastro commented
I have removed a couple of tasks in order to optimize the DAG here cfd7f12b50940f01f4dea9f67485292063d80156 .

2022-05-30 16:23 UTC, pankajastro commented on astronomer/providers/google/cloud/example_dags/example_dataproc.py
> +    create_cluster >> pig_task >> hive_task >> delete_cluster >> delete_bucket
Running it in less parallel so there will be minimal chance to fail because of unavailable resource

2022-05-31 05:41 UTC, phanikumv requested changes
PR title needs improvement. Summarize what you are doing here. If you are optimizing the example DAG, mention it as "Optimize example DAG for async google cloud operators".

2022-05-31 05:57 UTC, pankajastro commented
> PR title needs improvement. Summarize what you are doing here. If you are optimizing the example DAG, mention it as "Optimize example DAG for async google cloud operators".

I have improved a little bit and add added all the points that this PR addresses in the description.

2022-05-31 07:00 UTC, phanikumv approved these changes
lgtm

2022-05-31 07:00 UTC, merged