Implement Async WasbBlobSensor
astronomer/astronomer-providers pull request #92
Opened 2022-03-03 16:05 UTC by pohek321

2022-03-07 08:50 UTC, sunank200 requested changes
Overall, the implementation LGTM. The tests and an Example DAG are missing for the implementation. It would be good to add the test and an Example DAG as part of the PR. I have also added few comments and requested few changes on the PR.

2022-03-07 08:50 UTC, sunank200 commented on astronomer/providers/microsoft/cloud/triggers/wasb.py
> +        super().__init__()
`super().__init__()` can be removed as we are not using any of the `BaseTrigger` methods.

2022-03-07 08:50 UTC, sunank200 commented on astronomer/providers/microsoft/cloud/triggers/wasb.py
> +        Serializes GCSBlobTrigger arguments and classpath.
It should be `WasbBlobTrigger` instead of `GCSBlobTrigger`.

2022-03-07 08:50 UTC, sunank200 commented on astronomer/providers/microsoft/cloud/hooks/wasb.py
> +        with await self.get_conn() as conn:
Is `get_conn()` an async implementation because we are awaiting for it.

2022-03-07 08:50 UTC, sunank200 commented on astronomer/providers/microsoft/cloud/sensors/wasb.py
> +    def execute(self, context):
Type of `context` and return type of `execute()` are missing.

2022-03-07 08:50 UTC, sunank200 commented on astronomer/providers/microsoft/cloud/sensors/wasb.py
> +    def execute_complete(self, context, event=None):  # pylint: disable=unused-argument
Type of `context`, `event` and return type of `execute_complete()` are missing.

2022-03-07 08:50 UTC, sunank200 commented on astronomer/providers/microsoft/common/hooks/base_azure.py
> +    async def get_sync_hook(self):
Return type of `get_sync_hook()` is missing.

2022-03-08 11:33 UTC, phanikumv reviewed
Could you please check whether templating works for this operator 

`template_fields: Sequence[str] = ('container_name', 'blob_name')`

2022-07-04 14:00 UTC, pankajkoti commented
@phanikumv what should we do on this PR related to an open ticket https://app.zenhub.com/workspaces/airflow-providers-team-61a89ee7fbf048001dc8378d/issues/astronomer/astronomer-providers/92 . We have already merged PR https://github.com/astronomer/astronomer-providers/pull/482 against the ticket https://github.com/astronomer/astronomer-providers/issues/188 for the same ask.

2022-07-04 14:03 UTC, closed without merging