Remove unused param batch trigger
astronomer/astronomer-providers pull request #990
Opened 2023-04-25 17:08 UTC by pankajastro

2023-04-25 17:56 UTC, pankajkoti approved these changes
Nice cleanup actually. Please test the DAG once before merging.

2023-04-26 07:38 UTC, phanikumv requested changes
Waiting for test result on Astro

2023-04-26 09:41 UTC, pankajastro commented
> Waiting for test result on Astro

Tested on Astro!

<img width="538" alt="Screenshot 2023-04-26 at 3 10 35 PM" src="https://user-images.githubusercontent.com/98807258/234536767-2e9575d3-3341-4517-92eb-31e95d1f4e4a.png">

2023-04-26 10:04 UTC, phanikumv approved these changes

2023-04-26 10:04 UTC, merged